[project]
name = "deep-learning-final-project"
version = "0.1.0"
description = "Final Project for the Deep Learning course at Aarhus University Autumn 2023"
authors = ["kpbaks <kristoffer.pbs@tuta.io>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
format = { cmd = "ruff format ." }
lint = { cmd = "ruff check ." }
style = { depends_on = ["format", "lint"] }

[dependencies]
python = "3.10.0.*"
numpy = "1.26.0.*"
matplotlib = "3.8.1.*"
tqdm = "4.66.1.*"
ruff-lsp = "0.0.45.*"
ruff = "0.1.5.*"
jupytext = "1.15.2.*"
rich = "13.6.0.*"
pytorch = "2.0.0.*"
ipython = "8.17.2.*"
scipy = "1.11.3.*"
torchvision = "0.15.2.*"
scikit-learn = "1.3.2.*"
h5py = "3.10.0.*"
jupyter = "1.0.0.*"
tensorflow = "2.14.0.*"
librosa = "0.10.1.*"
intervaltree = "3.1.0.*"
pywavelets = "1.4.1.*"
