[project]
name = "deep-learning-final-project"
version = "0.1.0"
description = "Add a short description here"
authors = ["kpbaks <kristoffer.pbs@tuta.io>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.12.0.*"
numpy = "1.26.0.*"
matplotlib = "3.8.1.*"
tqdm = "4.66.1.*"
gymnasium = "0.26.3.*"
ruff-lsp = "0.0.45.*"
ruff = "0.1.5.*"
jupytext = "1.15.2.*"
rich = "13.6.0.*"
