[project]
name = "deep-learning-final-project"
version = "0.1.0"
description = "Final Project for the Deep Learning course at Aarhus University Autumn 2023"
authors = ["kpbaks <kristoffer.pbs@tuta.io>"]
channels = ["conda-forge", "pytorch"]
platforms = ["linux-64"]

[tasks]
format = { cmd = "ruff format ." }
lint = { cmd = "ruff check ." }
style = { depends_on = ["format", "lint"] }
jupyter = { cmd = "jupyter lab --no-browser" }

[dependencies]
ffmpeg = "<7"
ipykernel = "6.26.0.*"
ipython = "8.17.2.*"
jupyter = "1.0.0.*"
jupytext = "1.15.2.*"
librosa = "0.10.1.*"
loguru = "0.7.2.*"
matplotlib = "3.8.1.*"
numpy = "1.26.0.*"
pillow = "10.1.0.*"
pip = "23.3.1.*"
poetry = "1.7.1.*"
polars = "0.19.16.*"
pre-commit = "3.5.0.*"
python = "3.10.0.*"
pytorch = "2.0.0.*"
rich = "13.6.0.*"
ruff = "0.1.5.*"
ruff-lsp = "0.0.45.*"
scikit-learn = "1.3.2.*"
scipy = "1.11.3.*"
# torchaudio = "2.1.0.*"
# torchvision = "0.15.2.*"
tqdm = "4.66.1.*"
